import { StyleSheet } from "react-native";
import {
  colors,
  spacing,
  borderRadius,
  elevation,
  typography,
  fontWeights,
} from "../../theme";

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: colors.background,
  },

  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.backgroundAlt,
    borderRadius: borderRadius.lg,
    margin: spacing.md,
    paddingHorizontal: spacing.md,
    ...elevation.xs,
    height: 50,
    borderWidth: 1,
    borderColor: colors.border,
  },
  searchIcon: {
    marginRight: spacing.sm,
    color: colors.primary,
  },
  searchInput: {
    flex: 1,
    paddingVertical: spacing.md,
    fontSize: typography.body.medium.fontSize,
    color: colors.text,
  },
  headerRow: {
    flexDirection: "row",
    padding: spacing.md,
    backgroundColor: colors.backgroundAlt,
    margin: spacing.md,
    marginTop: spacing.xs,
    borderRadius: borderRadius.lg,
    alignItems: "center",
    ...elevation.xs,
    borderWidth: 1,
    borderColor: colors.border,
  },
  input: {
    flex: 1,
    height: 48,
    paddingHorizontal: spacing.md,
    backgroundColor: colors.backgroundAlt,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: colors.border,
    fontSize: typography.body.medium.fontSize,
    color: colors.text,
  },
  inputDisabled: {
    backgroundColor: colors.disabled,
  },
  uploadBtn: {
    marginLeft: spacing.md,
    backgroundColor: colors.primary,
    padding: spacing.sm,
    borderRadius: borderRadius.md,
    alignItems: "center",
    justifyContent: "center",
    height: 48,
    width: 48,
  },
  uploadBtnDisabled: {
    backgroundColor: `${colors.primary}80`,
  },
  card: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.backgroundAlt,
    marginHorizontal: spacing.md,
    marginVertical: spacing.sm,
    borderRadius: borderRadius.lg,
    ...elevation.sm,
    overflow: "hidden",
    borderLeftWidth: 3,
    borderLeftColor: colors.primary,
  },
  cardThumbnail: {
    width: 60,
    height: 80,
    borderTopLeftRadius: borderRadius.sm,
    borderBottomLeftRadius: borderRadius.sm,
    backgroundColor: colors.backgroundAlt,
  },
  thumbnailPlaceholder: {
    width: 60,
    height: 80,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.backgroundAlt,
  },
  cardContent: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    padding: spacing.md,
  },
  textContainer: {
    marginLeft: spacing.md,
    flex: 1,
  },
  title: {
    fontSize: typography.body.large.fontSize,
    fontWeight: fontWeights.semiBold,
    color: colors.text,
  },
  courseContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: spacing.xs,
    backgroundColor: colors.primaryLight,
    borderRadius: borderRadius.full,
    paddingHorizontal: spacing.sm,
    paddingVertical: 2,
    alignSelf: "flex-start",
  },
  courseText: {
    fontSize: typography.body.small.fontSize,
    color: colors.primary,
    fontWeight: fontWeights.medium,
  },
  date: {
    fontSize: typography.body.small.fontSize,
    color: colors.textSecondary,
    marginTop: spacing.xs,
  },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: spacing.xs,
  },
  uploader: {
    fontSize: typography.body.small.fontSize,
    color: colors.textSecondary,
  },
  deleteBtn: {
    backgroundColor: colors.error,
    padding: spacing.md,
    height: "100%",
    justifyContent: "center",
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: spacing.xl,
  },
  emptyText: {
    fontSize: typography.body.medium.fontSize,
    color: colors.textSecondary,
    textAlign: "center",
    marginTop: spacing.md,
  },
  filterChipsContainer: {
    flexDirection: "row",
    paddingHorizontal: spacing.md,
    marginBottom: spacing.md,
  },
  filterChip: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.full,
    marginRight: spacing.sm,
    backgroundColor: colors.backgroundAlt,
    borderWidth: 1,
    borderColor: colors.border,
    ...elevation.xs,
  },
  filterChipActive: {
    backgroundColor: colors.primaryLight,
    borderColor: colors.primary,
  },
  filterChipText: {
    fontSize: typography.body.small.fontSize,
    color: colors.textSecondary,
    fontWeight: fontWeights.medium,
  },
  filterChipTextActive: {
    color: colors.primary,
    fontWeight: fontWeights.bold,
  },
  fab: {
    position: "absolute",
    right: spacing.md,
    bottom: spacing.md,
    backgroundColor: colors.primary,
    width: 56,
    height: 56,
    borderRadius: borderRadius.full,
    justifyContent: "center",
    alignItems: "center",
    ...elevation.md,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: spacing.md,
  },
  modalContent: {
    backgroundColor: colors.backgroundAlt,
    borderRadius: borderRadius.lg,
    width: "100%",
    padding: spacing.lg,
    ...elevation.md,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: spacing.lg,
  },
  modalTitle: {
    fontSize: typography.heading.h4.fontSize,
    fontWeight: fontWeights.bold,
    color: colors.text,
  },
  inputLabel: {
    fontSize: typography.body.medium.fontSize,
    fontWeight: fontWeights.medium,
    color: colors.textSecondary,
    marginBottom: spacing.xs,
  },
  modalInput: {
    width: "100%",
    height: 48,
    paddingHorizontal: spacing.md,
    backgroundColor: colors.background,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: colors.border,
    fontSize: typography.body.medium.fontSize,
    color: colors.text,
    marginBottom: spacing.md,
  },
  uploadButton: {
    backgroundColor: colors.primary,
    padding: spacing.md,
    borderRadius: borderRadius.md,
    alignItems: "center",
    justifyContent: "center",
    height: 52,
    marginTop: spacing.md,
  },
  uploadButtonText: {
    color: "white",
    fontWeight: fontWeights.medium,
    fontSize: typography.body.medium.fontSize,
  },
});
