import { StyleSheet } from "react-native";
import {
  colors,
  fontSizes,
  fontWeights,
  spacing,
  borderRadius,
  elevation,
  typography,
} from "../../theme";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  container: { flex: 1, padding: spacing.md },
  sectionTitle: {
    ...typography.heading.h4,
    fontWeight: fontWeights.bold,
    marginBottom: spacing.md,
    color: colors.primary,
    textAlign: "center",
  },
  noEventText: {
    color: colors.textTertiary,
    fontSize: typography.body.small.fontSize,
    fontStyle: "italic",
    textAlign: "center",
    marginTop: spacing.md,
  },
  eventListContainer: { flex: 1, marginVertical: spacing.md },
  eventItem: {
    backgroundColor: colors.backgroundAlt,
    padding: spacing.md,
    borderRadius: borderRadius.md,
    shadowColor: elevation.sm.shadowColor,
    shadowOffset: elevation.sm.shadowOffset,
    shadowOpacity: elevation.sm.shadowOpacity,
    shadowRadius: elevation.sm.shadowRadius,
    elevation: elevation.sm.elevation,
    marginVertical: spacing.xs,
    marginHorizontal: spacing.xs,
    flexDirection: "row",
    alignItems: "center",
    borderLeftWidth: 3,
    borderLeftColor: colors.primary,
  },
  eventIcon: {
    marginRight: spacing.sm,
  },
  deleteButton: {
    backgroundColor: colors.error,
    justifyContent: "center",
    alignItems: "flex-end",
    borderRadius: borderRadius.sm,
    marginVertical: spacing.xs,
    paddingHorizontal: 20,
  },
  deleteButtonText: { color: colors.textInverse, fontWeight: "600" },
  eventTitle: { fontSize: fontSizes.md, fontWeight: "500", color: colors.text },
  eventContent: {
    flex: 1,
  },
  eventStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: spacing.xs,
  },
  eventStatus: {
    fontSize: fontSizes.xs,
    fontWeight: "600",
    marginLeft: 4,
  },
  clearAllButton: {
    backgroundColor: colors.errorAlt,
    paddingVertical: spacing.lg,
    borderRadius: borderRadius.sm,
    alignItems: "center",
    marginTop: spacing.lg,
    marginBottom: 90,
  },
  clearAllButtonText: { color: colors.textInverse, fontWeight: "600" },
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.4)",
    padding: spacing.xl,
  },
  modalContent: {
    backgroundColor: colors.backgroundAlt,
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    shadowColor: elevation.md.shadowColor,
    shadowOffset: elevation.md.shadowOffset,
    shadowOpacity: elevation.md.shadowOpacity,
    shadowRadius: elevation.md.shadowRadius,
    elevation: elevation.md.elevation,
    marginHorizontal: 0,
  },
  modalTitle: {
    fontSize: fontSizes.xl,
    fontWeight: "700",
    marginBottom: spacing.lg,
    color: colors.primary,
    textAlign: "center",
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: borderRadius.md,
    paddingHorizontal: spacing.md,
    height: 44,
    marginBottom: spacing.md,
    backgroundColor: colors.backgroundAlt,
    fontSize: fontSizes.md,
  },
  timePickerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: spacing.md,
  },
  timePickerLabel: {
    fontSize: fontSizes.md,
    color: colors.text,
    marginRight: spacing.md,
    fontWeight: "600",
  },
  timePickerButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: borderRadius.md,
    paddingVertical: 10,
    paddingHorizontal: spacing.md,
    backgroundColor: colors.backgroundAlt,
    alignItems: "center",
  },
  timePickerButtonText: {
    fontSize: fontSizes.md,
    color: colors.text,
  },
  eventTypeContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginBottom: spacing.lg,
    marginTop: spacing.md,
  },
  eventTypeButton: {
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: borderRadius.sm,
    borderWidth: 1,
    borderColor: colors.border,
    marginHorizontal: spacing.xs,
    backgroundColor: colors.backgroundAlt,
  },
  selectedEventTypeButton: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  eventTypeButtonText: {
    fontWeight: "600",
    color: colors.text,
  },
  selectedEventTypeText: {
    color: colors.textInverse,
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginTop: spacing.lg,
  },
  buttonCancel: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: borderRadius.sm,
    backgroundColor: colors.backgroundAlt,
    borderWidth: 1,
    borderColor: colors.secondary,
    marginRight: spacing.sm,
  },
  buttonCancelText: { color: colors.secondary, fontWeight: "600" },
  buttonSave: {
    backgroundColor: colors.secondary,
    borderRadius: borderRadius.sm,
    paddingVertical: 10,
    paddingHorizontal: 16,
  },
  buttonSaveText: { color: colors.textInverse, fontWeight: "600" },
  addEventButton: {
    position: "absolute",
    right: spacing.lg,
    bottom: spacing.lg,
    backgroundColor: colors.primary,
    borderRadius: 32,
    width: 56,
    height: 56,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: elevation.md.shadowColor,
    shadowOffset: elevation.md.shadowOffset,
    shadowOpacity: elevation.md.shadowOpacity,
    shadowRadius: elevation.md.shadowRadius,
    elevation: elevation.md.elevation,
    zIndex: 10,
  },
  addEventButtonText: {
    color: colors.textInverse,
    fontWeight: "700",
    fontSize: fontSizes.xl,
  },
  eventListHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: spacing.md,
    marginTop: spacing.md,
    paddingHorizontal: spacing.sm,
  },
  eventListTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  eventListTitleIcon: {
    marginRight: spacing.xs,
    color: colors.primary,
  },
  eventListTitle: {
    fontSize: fontSizes.xl,
    fontWeight: fontWeights.bold,
    color: colors.primary,
    letterSpacing: 0.2,
    textAlign: "left",
  },
  deleteAllIconBtn: {
    padding: spacing.sm,
    borderRadius: 20,
    backgroundColor: colors.errorAlt,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: spacing.md,
  },
  deleteAllIcon: {
    color: colors.textInverse,
  },
});
