import { StyleSheet } from "react-native";
import {
  colors,
  fontSizes,
  fontWeights,
  spacing,
  borderRadius,
  elevation,
  typography,
} from "../../theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: spacing.md,
    backgroundColor: colors.backgroundAlt,
  },
  center: { flex: 1, justifyContent: "center", alignItems: "center" },
  message: {
    fontSize: typography.body.medium.fontSize,
    color: colors.textSecondary,
  },
  title: {
    fontSize: typography.heading.h3.fontSize,
    lineHeight: typography.heading.h3.lineHeight,
    fontWeight: fontWeights.semiBold,
    marginBottom: spacing.md,
    color: colors.text,
  },
  meta: {
    fontSize: typography.body.small.fontSize,
    color: colors.textTertiary,
    marginBottom: spacing.xs,
  },
  backButton: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: spacing.md,
    paddingVertical: spacing.xs,
  },
  backText: {
    marginLeft: spacing.sm,
    fontSize: typography.body.medium.fontSize,
    color: colors.primary,
    fontWeight: fontWeights.semiBold,
  },
  metaRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: spacing.xs,
  },
  metaIcon: {
    marginRight: spacing.xs,
    color: colors.primary,
  },
  detailCard: {
    backgroundColor: colors.background,
    borderRadius: borderRadius.md,
    padding: spacing.md,
    shadowColor: elevation.sm.shadowColor,
    shadowOffset: elevation.sm.shadowOffset,
    shadowOpacity: elevation.sm.shadowOpacity,
    shadowRadius: elevation.sm.shadowRadius,
    elevation: elevation.sm.elevation,
    marginBottom: spacing.md,
    borderLeftWidth: 3,
    borderLeftColor: colors.primary,
  },
  statusBadge: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    marginBottom: spacing.md,
    alignSelf: "flex-start",
  },
  statusIcon: {
    marginRight: 4,
  },
  statusText: {
    color: "white",
    fontSize: fontSizes.sm,
    fontWeight: "600",
  },
  expiredNotice: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f0f0f0",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    marginBottom: spacing.md,
  },
  noticeIcon: {
    marginRight: 6,
  },
  expiredText: {
    fontSize: fontSizes.sm,
    color: "#666",
    fontStyle: "italic",
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.4)",
    padding: spacing.xl,
  },
  modalContent: {
    backgroundColor: colors.background,
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    shadowColor: colors.shadow,
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 12,
    elevation: 4,
    marginHorizontal: 0,
  },
  modalTitle: {
    fontSize: fontSizes.xl,
    fontWeight: "700",
    marginBottom: spacing.lg,
    color: colors.primary,
    textAlign: "center",
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: borderRadius.md,
    paddingHorizontal: spacing.md,
    height: 44,
    marginBottom: spacing.md,
    backgroundColor: colors.backgroundAlt,
    fontSize: fontSizes.md,
  },
  timePickerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: spacing.md,
  },
  timePickerLabel: {
    fontSize: fontSizes.md,
    color: colors.text,
    marginRight: spacing.md,
    fontWeight: "600",
  },
  timePickerButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: borderRadius.md,
    paddingVertical: 10,
    paddingHorizontal: spacing.md,
    backgroundColor: colors.backgroundAlt,
    alignItems: "center",
  },
  timePickerButtonText: {
    fontSize: fontSizes.md,
    color: colors.text,
  },
  eventTypeContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginBottom: spacing.lg,
    marginTop: spacing.md,
  },
  eventTypeButton: {
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: borderRadius.sm,
    borderWidth: 1,
    borderColor: colors.border,
    marginHorizontal: spacing.xs,
    backgroundColor: colors.backgroundAlt,
  },
  selectedEventTypeButton: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  eventTypeButtonText: {
    fontWeight: "600",
    color: colors.text,
  },
  selectedEventTypeText: {
    color: colors.textInverse,
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginTop: spacing.lg,
  },
  buttonCancel: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: borderRadius.sm,
    backgroundColor: colors.backgroundAlt,
    borderWidth: 1,
    borderColor: colors.secondary,
    marginRight: spacing.sm,
  },
  buttonCancelText: { color: colors.secondary, fontWeight: "600" },
  buttonSave: {
    backgroundColor: colors.secondary,
    borderRadius: borderRadius.sm,
    paddingVertical: 10,
    paddingHorizontal: 16,
  },
  buttonSaveText: { color: colors.textInverse, fontWeight: "600" },
});
