import { StyleSheet } from "react-native";
import {
  colors,
  fontSizes,
  spacing,
  borderRadius,
  typography,
  fontWeights,
  elevation,
} from "../../theme";

export const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: colors.background,
    padding: spacing.lg,
  },
  headerContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: spacing.xl,
    position: "relative",
  },
  backButton: {
    position: "absolute",
    left: 0,
    padding: spacing.sm,
  },
  header: {
    fontSize: typography.heading.h5.fontSize,
    fontWeight: fontWeights.bold,
    color: colors.primary,
  },
  label: {
    fontSize: fontSizes.md,
    fontWeight: fontWeights.medium,
    color: colors.text,
    marginBottom: spacing.sm,
    marginLeft: spacing.sm,
  },
  input: {
    backgroundColor: colors.backgroundAlt,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
    borderRadius: borderRadius.lg,
    marginBottom: spacing.lg,
    fontSize: fontSizes.md,
    color: colors.text,
  },
  switchContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: spacing.xl,
    backgroundColor: colors.backgroundAlt,
    padding: spacing.md,
    borderRadius: borderRadius.lg,
    borderWidth: 1,
    borderColor: colors.border,
  },
  switchLabel: {
    fontSize: fontSizes.md,
    color: colors.text,
    flex: 1,
  },
  checkboxContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  checkbox: {
    width: 20,
    height: 20,
    borderWidth: 2,
    borderColor: colors.border,
    borderRadius: 4,
    marginLeft: spacing.sm,
    justifyContent: "center",
    alignItems: "center",
  },
  checkboxChecked: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  button: {
    backgroundColor: colors.primary,
    padding: spacing.md,
    borderRadius: borderRadius.lg,
    alignItems: "center",
    ...elevation.sm,
  },
  buttonText: {
    color: colors.textInverse,
    fontSize: fontSizes.lg,
    fontWeight: fontWeights.bold,
  },
  tipContainer: {
    backgroundColor: colors.primaryLight,
    padding: spacing.md,
    borderRadius: borderRadius.lg,
    marginTop: spacing.xl,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.primary,
    borderStyle: "dashed",
  },
  tipText: {
    color: colors.primary,
    fontSize: fontSizes.sm,
    marginLeft: spacing.sm,
    flex: 1,
    lineHeight: 18,
  },
});
