import { StyleSheet } from "react-native";
import {
  colors,
  spacing,
  borderRadius,
  typography,
  elevation,
  fontWeights,
} from "../../theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    paddingTop: spacing.lg,
    paddingBottom: spacing.sm,
    paddingHorizontal: spacing.md,
    backgroundColor: colors.background,
  },
  headerTitle: {
    fontSize: typography.heading.h3.fontSize,
    fontWeight: fontWeights.bold,
    color: colors.text,
    marginBottom: spacing.sm,
  },
  headerSubtitle: {
    fontSize: typography.body.medium.fontSize,
    color: colors.textSecondary,
    marginBottom: spacing.md,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.backgroundAlt,
    borderRadius: borderRadius.lg,
    margin: spacing.md,
    paddingHorizontal: spacing.md,
    ...elevation.xs,
    height: 50,
    borderWidth: 1,
    borderColor: colors.border,
  },
  searchIcon: {
    marginRight: spacing.sm,
    color: colors.primary,
  },
  searchInput: {
    flex: 1,
    paddingVertical: spacing.md,
    fontSize: typography.body.medium.fontSize,
    color: colors.text,
  },
  filterChipsContainer: {
    flexDirection: "row",
    paddingHorizontal: spacing.md,
    marginBottom: spacing.md,
  },
  filterChip: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.full,
    marginRight: spacing.sm,
    backgroundColor: colors.backgroundAlt,
    borderWidth: 1,
    borderColor: colors.border,
    ...elevation.xs,
  },
  filterChipActive: {
    backgroundColor: colors.primaryLight,
    borderColor: colors.primary,
  },
  filterChipText: {
    fontSize: typography.body.small.fontSize,
    color: colors.textSecondary,
    fontWeight: fontWeights.medium,
  },
  filterChipTextActive: {
    color: colors.primary,
    fontWeight: fontWeights.bold,
  },
  title: {
    fontWeight: fontWeights.bold,
    fontSize: typography.heading.h5.fontSize,
    marginBottom: spacing.sm,
    flex: 1,
    color: colors.text,
  },
  questionBox: {
    backgroundColor: colors.backgroundAlt,
    padding: spacing.lg,
    borderRadius: borderRadius.lg,
    marginVertical: spacing.sm,
    marginHorizontal: spacing.md,
    ...elevation.sm,
    borderLeftWidth: 3,
    borderLeftColor: colors.accent,
  },
  questionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: spacing.xs,
  },
  courseContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: spacing.xs,
    backgroundColor: colors.primaryLight,
    borderRadius: borderRadius.full,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    alignSelf: "flex-start",
  },
  course: {
    color: colors.primary,
    fontSize: typography.body.small.fontSize,
    fontWeight: fontWeights.medium,
  },
  metaInfoContainer: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    marginTop: spacing.sm,
    backgroundColor: colors.background,
    borderRadius: borderRadius.md,
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.sm,
  },
  metaInfoDivider: {
    height: 4,
    width: 4,
    borderRadius: 2,
    backgroundColor: colors.textTertiary,
    marginHorizontal: spacing.sm,
  },
  author: {
    fontSize: typography.body.small.fontSize,
    color: colors.textSecondary,
    flexDirection: "row",
    alignItems: "center",
  },
  timestamp: {
    fontSize: typography.body.xsmall.fontSize,
    color: colors.textTertiary,
    flexDirection: "row",
    alignItems: "center",
  },
  metaInfo: {
    fontSize: typography.body.small.fontSize,
    color: colors.textSecondary,
    flexDirection: "row",
    alignItems: "center",
  },
  deleteBtn: {
    padding: spacing.xs,
  },
  fab: {
    position: "absolute",
    right: spacing.md,
    bottom: spacing.md,
    backgroundColor: colors.primary,
    width: 56,
    height: 56,
    borderRadius: borderRadius.full,
    justifyContent: "center",
    alignItems: "center",
    ...elevation.md,
  },
  emptyContainer: {
    padding: spacing.xl,
    alignItems: "center",
    justifyContent: "center",
    marginTop: spacing.xl,
  },
  emptyText: {
    textAlign: "center",
    marginTop: spacing.md,
    color: colors.textSecondary,
    fontSize: typography.body.medium.fontSize,
  },
});
