import { StyleSheet } from "react-native";
import {
  colors,
  fontSizes,
  spacing,
  borderRadius,
  fontWeights,
  elevation,
  typography,
} from "../../theme";

export const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: colors.background,
    padding: spacing.lg,
  },
  backButton: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: spacing.lg,
  },
  backText: {
    marginLeft: spacing.sm,
    fontSize: fontSizes.md,
    color: colors.primary,
    fontWeight: fontWeights.semiBold,
  },
  questionBox: {
    backgroundColor: colors.backgroundAlt,
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    marginBottom: spacing.xl,
    ...elevation.sm,
    borderLeftWidth: 3,
    borderLeftColor: colors.accent,
  },
  title: {
    fontSize: fontSizes.xl,
    fontWeight: fontWeights.bold,
    marginBottom: spacing.md,
    color: colors.text,
    lineHeight: fontSizes.xl * 1.4,
  },
  subtitleContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: spacing.md,
    backgroundColor: colors.primaryLight,
    borderRadius: borderRadius.full,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    alignSelf: "flex-start",
  },
  subtitle: {
    fontSize: fontSizes.md,
    color: colors.primary,
    fontWeight: fontWeights.medium,
  },
  authorContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: spacing.md,
    flexWrap: "wrap",
    backgroundColor: colors.background,
    padding: spacing.sm,
    borderRadius: borderRadius.md,
  },
  authorText: {
    fontSize: fontSizes.sm,
    color: colors.textSecondary,
  },
  timestampText: {
    fontSize: fontSizes.sm,
    color: colors.textSecondary,
  },
  body: {
    fontSize: fontSizes.md,
    color: colors.text,
    lineHeight: 24,
    marginBottom: spacing.md,
  },
  sectionTitle: {
    fontSize: typography.heading.h5.fontSize,
    fontWeight: fontWeights.bold,
    marginTop: spacing.xl,
    marginBottom: spacing.md,
    color: colors.primary,
  },
  answer: {
    marginBottom: spacing.lg,
    padding: spacing.lg,
    backgroundColor: colors.backgroundAlt,
    borderRadius: borderRadius.lg,
    ...elevation.xs,
    borderLeftWidth: 3,
    borderLeftColor: colors.placeholder,
  },
  answerBody: {
    fontSize: fontSizes.md,
    color: colors.text,
    lineHeight: 22,
  },
  answerMeta: {
    fontSize: fontSizes.sm,
    color: colors.textSecondary,
    marginTop: spacing.md,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.lg,
    borderRadius: borderRadius.lg,
    marginBottom: spacing.md,
    fontSize: fontSizes.md,
    backgroundColor: colors.backgroundAlt,
    color: colors.text,
  },
  switchContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: spacing.lg,
    backgroundColor: colors.backgroundAlt,
    padding: spacing.md,
    borderRadius: borderRadius.lg,
    borderWidth: 1,
    borderColor: colors.border,
  },
  checkboxContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  checkbox: {
    width: 20,
    height: 20,
    borderWidth: 2,
    borderColor: colors.border,
    borderRadius: 4,
    marginLeft: spacing.sm,
    justifyContent: "center",
    alignItems: "center",
  },
  checkboxChecked: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  checkboxLabel: {
    fontSize: fontSizes.md,
    color: colors.text,
    flex: 1,
  },
  answerActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: spacing.md,
    alignItems: "center",
    marginLeft: spacing.sm,
  },
  editActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginTop: spacing.md,
    gap: 10,
  },
  noAnswer: {
    textAlign: "center",
    color: colors.textSecondary,
    marginVertical: spacing.xl,
    fontSize: fontSizes.md,
    backgroundColor: colors.backgroundAlt,
    padding: spacing.lg,
    borderRadius: borderRadius.lg,
    borderStyle: "dashed",
    borderWidth: 1,
    borderColor: colors.border,
  },
  button: {
    backgroundColor: colors.primary,
    padding: spacing.md,
    borderRadius: borderRadius.lg,
    alignItems: "center",
    minWidth: 100,
    ...elevation.xs,
  },
  buttonText: {
    color: colors.textInverse,
    fontSize: fontSizes.md,
    fontWeight: fontWeights.bold,
  },
  upvoteContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: colors.primaryLight,
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
    borderRadius: borderRadius.full,
    ...elevation.xs,
  },
  upvoteCount: {
    fontSize: fontSizes.sm,
    color: colors.primary,
    fontWeight: fontWeights.semiBold,
  },
  answerMetaContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: spacing.md,
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  answerMetaLeft: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    flex: 1,
  },
  answerMetaRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  metaItem: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: spacing.sm,
  },
  metaText: {
    fontSize: fontSizes.sm,
    color: colors.textSecondary,
    marginLeft: 4,
  },
});
