import { StyleSheet } from "react-native";
import {
  colors,
  fontSizes,
  fontWeights,
  spacing,
  borderRadius,
  elevation,
  typography,
} from "../../theme";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  loadingContainer: { flex: 1, justifyContent: "center", alignItems: "center" },
  categoriesContainer: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    paddingBottom: spacing.md,
  },
  catCard: {
    width: 200,
    height: 180,
    borderRadius: borderRadius.lg,
    backgroundColor: colors.primary,
    marginRight: spacing.md,
    overflow: "hidden",
    ...elevation.md,
    position: "relative",
  },
  catPattern: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    opacity: 0.1,
    zIndex: 0,
  },
  catCardContent: {
    padding: spacing.md,
    height: "100%",
    justifyContent: "space-between",
    zIndex: 2,
  },
  catGradientOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.3)",
    zIndex: 1,
  },
  catIconContainer: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "rgba(255,255,255,0.2)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: spacing.md,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.3)",
  },
  catBadge: {
    position: "absolute",
    top: spacing.md,
    right: spacing.md,
    backgroundColor: "rgba(255,255,255,0.9)",
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xxs,
    borderRadius: borderRadius.full,
    zIndex: 3,
  },
  catBadgeText: {
    color: colors.primary,
    fontSize: fontSizes.xs,
    fontWeight: fontWeights.semiBold,
  },
  catTitle: {
    color: colors.textInverse,
    fontSize: fontSizes.sm,
    fontWeight: fontWeights.semiBold,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: spacing.xs,
  },
  catName: {
    color: colors.textInverse,
    fontSize: fontSizes.lg,
    fontWeight: fontWeights.bold,
    marginBottom: spacing.xs,
    textShadowColor: "rgba(0,0,0,0.5)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  catSub: {
    color: colors.textInverse,
    fontSize: fontSizes.sm,
    opacity: 0.9,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.backgroundAlt,
    marginHorizontal: spacing.lg,
    marginVertical: spacing.md,
    paddingHorizontal: spacing.md,
    borderRadius: borderRadius.lg,
    height: 50,
    borderWidth: 1,
    borderColor: colors.border,
    ...elevation.xs,
  },
  searchInput: {
    flex: 1,
    marginLeft: spacing.sm,
    fontSize: fontSizes.md,
    color: colors.text,
  },
  listContainer: {
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.lg,
  },
  sectionTitle: {
    fontSize: typography.heading.h5.fontSize,
    fontWeight: fontWeights.semiBold,
    color: colors.primary,
    marginHorizontal: spacing.lg,
    marginTop: spacing.lg,
    position: "relative",
  },
  emptyText: {
    fontStyle: "italic",
    color: colors.placeholder,
    textAlign: "center",
    marginTop: spacing.xl,
    fontSize: fontSizes.md,
  },
  emptyFeaturedContainer: {
    padding: spacing.xl,
    alignItems: "center",
    justifyContent: "center",
  },
  card: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.backgroundAlt,
    padding: spacing.md,
    borderRadius: borderRadius.lg,
    marginVertical: spacing.sm,
    ...elevation.sm,
    borderLeftWidth: 3,
    borderLeftColor: colors.warning,
  },
  cardPressed: {
    opacity: 0.8,
    backgroundColor: colors.primaryLight,
  },
  avatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: colors.primary,
    justifyContent: "center",
    alignItems: "center",
    marginRight: spacing.md,
  },
  info: { flex: 1 },
  name: {
    fontSize: fontSizes.md,
    fontWeight: fontWeights.semiBold,
    color: colors.text,
    marginBottom: spacing.xs,
  },
  subjectContainer: {
    alignSelf: "flex-start",
    marginBottom: spacing.xs,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.primaryLight,
    borderRadius: borderRadius.full,
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
  },
  subjectIcon: {
    marginRight: spacing.xs,
  },
  subject: {
    fontSize: typography.body.small.fontSize,
    color: colors.primary,
    fontWeight: fontWeights.medium,
    overflow: "hidden",
  },
  ratingContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: spacing.xs,
  },
  ratingLabel: {
    fontSize: fontSizes.sm,
    color: colors.textSecondary,
    marginRight: spacing.xs,
  },
  ratingStars: {
    flexDirection: "row",
  },
  ratingValue: {
    fontSize: fontSizes.sm,
    fontWeight: fontWeights.semiBold,
    color: colors.primary,
    marginLeft: spacing.xs,
  },
});
