import { StyleSheet } from "react-native";
import {
  colors,
  fontSizes,
  fontWeights,
  spacing,
  borderRadius,
  elevation,
  typography,
} from "../../theme";

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: colors.background,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  headerContainer: {
    backgroundColor: colors.backgroundAlt,
    borderBottomLeftRadius: borderRadius.lg,
    borderBottomRightRadius: borderRadius.lg,
    padding: spacing.lg,
    marginBottom: spacing.lg,
    ...elevation.md,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: spacing.md,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.background,
    alignItems: "center",
    justifyContent: "center",
    ...elevation.xs,
  },
  title: {
    fontSize: typography.heading.h3.fontSize,
    lineHeight: typography.heading.h3.lineHeight,
    fontWeight: fontWeights.bold,
    color: colors.primary,
    flex: 1,
    marginLeft: spacing.md,
  },
  subjectRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: spacing.md,
    flexWrap: "wrap",
    paddingBottom: spacing.md,
  },
  subLabel: {
    fontSize: typography.body.medium.fontSize,
    fontWeight: fontWeights.semiBold,
    color: colors.textSecondary,
    marginRight: spacing.sm,
  },
  subjectText: {
    fontSize: typography.body.medium.fontSize,
    color: colors.text,
    flexShrink: 1,
  },
  subjectBadgeContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
  },
  subjectIcon: {
    marginRight: spacing.xs,
  },
  subjectBadge: {
    fontSize: typography.body.small.fontSize,
    color: colors.primary,
    fontWeight: fontWeights.medium,
    backgroundColor: colors.primaryLight,
    borderRadius: borderRadius.full,
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
    overflow: "hidden",
  },
  avgRowCompact: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.primaryLight,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.full,
  },
  avgText: {
    fontSize: typography.body.medium.fontSize,
    fontWeight: fontWeights.semiBold,
    marginLeft: spacing.xs,
    color: colors.primary,
  },
  section: {
    fontSize: typography.heading.h5.fontSize,
    fontWeight: fontWeights.semiBold,
    color: colors.primary,
    marginBottom: spacing.md,

    marginHorizontal: spacing.lg,
  },
  sectionContainer: {
    marginBottom: spacing.xl,
  },
  starsRow: {
    flexDirection: "row",
    marginBottom: spacing.md,
    justifyContent: "center",
    backgroundColor: colors.backgroundAlt,
    padding: spacing.md,
    borderRadius: borderRadius.lg,
    marginHorizontal: spacing.lg,
    ...elevation.xs,
  },
  star: {
    marginHorizontal: spacing.xs,
  },
  input: {
    backgroundColor: colors.backgroundAlt,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
    marginHorizontal: spacing.lg,
    marginBottom: spacing.md,
    minHeight: 100,
    textAlignVertical: "top",
    color: colors.text,
    ...elevation.xs,
  },
  sendButton: {
    backgroundColor: colors.primary,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.md,
    alignItems: "center",
    marginTop: spacing.md,
    marginHorizontal: spacing.lg,
    marginBottom: spacing.xxl,
    ...elevation.sm,
  },
  sendButtonText: {
    color: colors.textInverse,
    fontWeight: fontWeights.semiBold,
    fontSize: fontSizes.md,
  },
  commentCard: {
    backgroundColor: colors.backgroundAlt,
    marginHorizontal: spacing.lg,
    marginVertical: spacing.sm,
    padding: spacing.md,
    borderRadius: borderRadius.lg,
    ...elevation.sm,
    borderLeftWidth: 3,
    borderLeftColor: colors.warning,
  },
  commentHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: spacing.md,
    paddingBottom: spacing.sm,
  },
  starsRowSmall: {
    flexDirection: "row",
    alignItems: "center",
  },
  starSmall: {
    marginRight: spacing.xxs,
  },
  ratingDateContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
  },
  dateText: {
    fontSize: fontSizes.xs,
    color: colors.textTertiary,
    fontStyle: "italic",
  },
  emptyContainer: {
    alignItems: "center",
    justifyContent: "center",
    padding: spacing.xl,
    backgroundColor: colors.backgroundAlt,
    borderRadius: borderRadius.lg,
    marginHorizontal: spacing.lg,
    marginBottom: spacing.xl,
  },
  commentActionsContainer: {
    flexDirection: "row",
    gap: spacing.md,
  },
  commentAction: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.background,
  },
  commentText: {
    fontSize: typography.body.medium.fontSize,
    color: colors.text,
    marginTop: spacing.xs,
    marginBottom: spacing.md,
    lineHeight: typography.body.medium.lineHeight,
  },
  likeDislikeRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  likeButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.background,
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.sm,
    borderRadius: borderRadius.full,
    marginRight: spacing.md,
  },
  likeButtonActive: {
    backgroundColor: colors.primaryLight,
  },
  dislikeButtonActive: {
    backgroundColor: `${colors.error}20`,
  },
  iconCount: {
    fontSize: fontSizes.sm,
    color: colors.textSecondary,
    marginLeft: spacing.xs,
  },
  empty: {
    textAlign: "center",
    fontStyle: "italic",
    color: colors.placeholder,
    marginTop: spacing.md,
    fontSize: fontSizes.md,
  },
  buttonRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: spacing.md,
    marginTop: spacing.md,
  },
  cancelButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    backgroundColor: colors.background,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  cancelButtonText: {
    marginLeft: spacing.xs,
    fontSize: fontSizes.sm,
    color: colors.text,
    fontWeight: fontWeights.medium,
  },
  saveButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    backgroundColor: colors.primary,
    borderRadius: borderRadius.md,
    ...elevation.xs,
  },
  saveButtonText: {
    marginLeft: spacing.xs,
    fontSize: fontSizes.sm,
    color: colors.textInverse,
    fontWeight: fontWeights.semiBold,
  },
  divider: {
    height: 1,
    backgroundColor: colors.border,
    marginVertical: spacing.lg,
    marginHorizontal: spacing.lg,
  },
});
