import { StyleSheet } from "react-native";
import {
  colors,
  fontSizes,
  fontWeights,
  spacing,
  borderRadius,
  elevation,
  typography,
} from "../../theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollContent: {
    flexGrow: 1,
    padding: spacing.lg,
    paddingBottom: spacing.xxl * 2,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.background,
  },

  heroSection: {
    width: "100%",
    backgroundColor: colors.primary,
    borderRadius: borderRadius.lg,
    marginBottom: spacing.xl,
    overflow: "hidden",
    position: "relative",
    ...elevation.md,
  },
  heroPattern: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    opacity: 0.08,
  },
  heroContent: {
    padding: spacing.lg,
    alignItems: "center",
    paddingBottom: spacing.xl,
  },
  profileHeader: {
    width: "100%",
    alignItems: "center",
    marginTop: spacing.md,
  },
  avatarContainer: {
    position: "relative",
    marginBottom: spacing.md,
    alignItems: "center",
    ...elevation.md,
  },
  avatar: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: colors.primaryLight,
    borderWidth: 3,
    borderColor: colors.backgroundAlt,
  },
  avatarFallback: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: colors.primaryLight,
    borderWidth: 3,
    borderColor: colors.backgroundAlt,
    justifyContent: "center",
    alignItems: "center",
  },
  cameraIconContainer: {
    position: "absolute",
    bottom: 0,
    right: 0,
    backgroundColor: colors.secondary,
    borderRadius: borderRadius.full,
    padding: spacing.xs,
    borderWidth: 2,
    borderColor: colors.backgroundAlt,
    ...elevation.sm,
  },
  nameText: {
    color: colors.textInverse,
    fontSize: typography.heading.h4.fontSize,
    fontWeight: fontWeights.bold,
    marginTop: spacing.sm,
  },
  emailText: {
    fontSize: fontSizes.sm,
    color: colors.backgroundAlt,
    fontWeight: fontWeights.medium,
    opacity: 0.9,
    marginTop: spacing.xs,
  },

  cardContainer: {
    width: "100%",
    marginBottom: spacing.sm,
  },
  formSection: {
    width: "100%",
    backgroundColor: colors.backgroundAlt,
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    marginBottom: spacing.lg,
    ...elevation.sm,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: spacing.md,
  },
  sectionIcon: {
    marginRight: spacing.sm,
    backgroundColor: colors.primaryLight,
    width: 32,
    height: 32,
    borderRadius: borderRadius.full,
    justifyContent: "center",
    alignItems: "center",
  },
  sectionTitle: {
    fontSize: typography.heading.h5.fontSize,
    fontWeight: fontWeights.semiBold,
    color: colors.primary,
  },
  inputContainer: {
    width: "100%",
    marginBottom: spacing.lg,
  },
  inputLabel: {
    fontSize: fontSizes.sm,
    color: colors.textSecondary,
    marginBottom: spacing.xs,
    fontWeight: fontWeights.medium,
  },
  input: {
    width: "100%",
    height: 50,
    backgroundColor: colors.background,
    borderRadius: borderRadius.md,
    paddingHorizontal: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    fontSize: fontSizes.md,
    ...elevation.xs,
  },
  dropdownButton: {
    width: "100%",
    height: 50,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: borderRadius.md,
    backgroundColor: colors.background,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: spacing.md,
    ...elevation.xs,
  },
  dropdownButtonText: {
    fontSize: fontSizes.md,
    color: colors.text,
  },
  dropdownButtonContent: {
    height: 50,
    alignItems: "center",
    justifyContent: "flex-start",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    width: "80%",
    maxHeight: 300,
    backgroundColor: colors.backgroundAlt,
    borderRadius: borderRadius.md,
    padding: spacing.md,
    ...elevation.lg,
  },
  dropdownItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  dropdownItemIcon: {
    marginRight: spacing.sm,
  },
  dropdownItemText: {
    fontSize: fontSizes.md,
    color: colors.text,
  },

  roleContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: spacing.md,
    padding: spacing.md,
    borderRadius: borderRadius.md,
    backgroundColor: colors.primaryLight,
  },
  roleIcon: {
    color: colors.primary,
  },
  roleText: {
    marginLeft: spacing.sm,
    fontSize: fontSizes.md,
    color: colors.primary,
    fontWeight: fontWeights.semiBold,
  },
  actionButtonsContainer: {
    width: "100%",
    alignItems: "center",
  },
  divider: {
    width: "100%",
    marginVertical: spacing.lg,
    backgroundColor: colors.border,
    height: 1,
  },
  saveButton: {
    width: "100%",
    marginBottom: spacing.md,
    borderRadius: borderRadius.md,
    paddingVertical: spacing.sm,
    height: 54,
    backgroundColor: colors.primary,
    justifyContent: "center",
    alignItems: "center",
    ...elevation.sm,
  },
  saveButtonDisabled: {
    backgroundColor: colors.primaryLight,
    opacity: 0.7,
  },
  saveButtonText: {
    color: colors.textInverse,
    fontWeight: fontWeights.semiBold,
    fontSize: fontSizes.md,
  },
  signOutButton: {
    borderColor: colors.error,
    borderWidth: 1,
    borderRadius: borderRadius.md,
    width: "40%",
    marginTop: spacing.md,
    paddingVertical: spacing.sm,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  signOutText: {
    color: colors.error,
    fontWeight: fontWeights.semiBold,
  },
});
