import { StyleSheet } from "react-native";
import {
  colors,
  fontWeights,
  spacing,
  borderRadius,
  elevation,
  typography,
} from "../../theme";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  container: { flex: 1, padding: spacing.md },
  inputRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.backgroundAlt,
    borderRadius: borderRadius.lg,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    shadowColor: elevation.xs.shadowColor,
    shadowOpacity: elevation.xs.shadowOpacity,
    shadowOffset: elevation.xs.shadowOffset,
    shadowRadius: elevation.xs.shadowRadius,
    elevation: elevation.xs.elevation,
  },
  input: {
    flex: 1,
    height: 48,
    fontSize: typography.body.medium.fontSize,
    color: colors.text,
    paddingHorizontal: spacing.sm,
  },
  addButton: {
    marginLeft: spacing.sm,
    backgroundColor: colors.primary,
    width: 44,
    height: 44,
    borderRadius: borderRadius.round,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: elevation.sm.shadowColor,
    shadowOpacity: elevation.sm.shadowOpacity,
    shadowOffset: elevation.sm.shadowOffset,
    shadowRadius: elevation.sm.shadowRadius,
    elevation: elevation.sm.elevation,
  },
  summaryText: {
    textAlign: "center",
    marginVertical: spacing.md,
    color: colors.textSecondary,
    fontSize: typography.body.small.fontSize,
    fontWeight: fontWeights.bold,
  },
  listContainer: { paddingBottom: spacing.lg },
  todoCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.backgroundAlt,
    padding: spacing.md,
    borderRadius: borderRadius.md,
    marginVertical: spacing.xs,
    shadowColor: elevation.sm.shadowColor,
    shadowOpacity: elevation.sm.shadowOpacity,
    shadowOffset: elevation.sm.shadowOffset,
    shadowRadius: elevation.sm.shadowRadius,
    elevation: elevation.sm.elevation,
    borderLeftWidth: 3,
    borderLeftColor: colors.primary,
  },
  doneCard: {
    opacity: 0.6,
    borderLeftColor: colors.success,
  },
  todoText: {
    flex: 1,
    fontSize: typography.body.medium.fontSize,
    color: colors.text,
    marginLeft: spacing.md,
  },
  doneText: {
    textDecorationLine: "line-through",
    color: colors.placeholder,
  },
  emptyText: {
    textAlign: "center",
    color: colors.placeholder,
    fontStyle: "italic",
    marginTop: spacing.xl,
    fontSize: typography.body.medium.fontSize,
  },
});
